### PR TITLE
Fix "couldn't find the config" after @logux/eslint-config update to 36.0.0. Remove separated browser and node configs.

### PR DESCRIPTION
**Pull request by yunusga**
After update `@logux/eslint-config    35.0.4  →   36.0.0` test for postcss plugins failed

```sh
node: v12.14.0
eslint: 6.8.0
@logux/eslint-config:  36.0.0
eslint-config-postcss: 3.0.7
```

### Error

```bash
ESLint couldn't find the config "@logux/eslint-config/node" to extend from. Please check that the name of the config is correct.

The config "@logux/eslint-config/node" was referenced from the config file in "C:\Users\Yunus\Projects\postcss-momentum-scrolling\node_modules\eslint-config-postcss\index.js".
```

### Complete log

```bash
$ npm run test

> postcss-momentum-scrolling@2.3.14 test C:\Users\Yunus\Projects\postcss-momentum-scrolling
> jest && eslint . --fix

 PASS  ./index.test.js
  √ if has momentum scroll, do nothing (24ms)
  √ custom options (hidden, inherit) (18ms)
  √ if options is not array (1ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        1.826s
Ran all test suites.

Oops! Something went wrong! :(

ESLint: 6.8.0.

ESLint couldn't find the config "@logux/eslint-config/node" to extend from. Please check that the name of the config is correct.

The config "@logux/eslint-config/node" was referenced from the config file in "C:\Users\Yunus\Projects\postcss-momentum-scrolling\node_modules\eslint-config-postcss\index.js".

If you still have problems, please stop by https://gitter.im/eslint/eslint to chat with the team.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! postcss-momentum-scrolling@2.3.14 test: `jest && eslint . --fix`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the postcss-momentum-scrolling@2.3.14 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Yunus\AppData\Roaming\npm-cache\_logs\2020-02-18T06_14_10_445Z-debug.log
```

### CODE REVIEW

**Comment by yunusga** [comment]
I think this package no longer need to install, because [@logux/eslint-config](https://github.com/logux/eslint-config) do same thing.

**Comment by ai** [comment]
Can you remove `ChangeLog` changes. I bump the version and add change log in separated “release” commit only.

**Comment by yunusga** [comment]
@ai Ok, removed `ChangeLog` changes in 9f49fcd

**Comment by ai** [comment]
Thanks. Released at 4.0.0

**Pull request merged**
